#!/usr/bin/env sh

set -e

RCLONE_CONF=/config/rclone/rclone.conf

if [ ! -f "$RCLONE_CONF" ]; then
    mkdir -p "$(dirname "$RCLONE_CONF")"
    echo "$RCLONE_CONFIG_SEED" | base64 -d >"$RCLONE_CONF"
fi


while true; do
    # if dir not empty
    if [ "$(ls -A "$SOURCE")" ]; then

        # wait for files to stop changing
        files=""
        while true; do
            echo "Waiting for files to stop changing..."
            new_files="$(find "$SOURCE" -type f -print0 | xargs -0 stat -c '%n %Y')"
            if [ "$files" != "$new_files" ]; then
                files="$new_files"
                sleep 5
            else
                break
            fi
        done

        nice -n 10 \
            rclone \
                move "$SOURCE" "$DEST" \
                --progress \
                --delete-empty-src-dirs
    else
        sleep 60
    fi
done
